import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
     <header> 
     <nav>
      <Link href="/">Inicio</Link> |{" "}
      <Link href="/opiniones">Opiniones</Link> |{" "}
      <Link href="/contacto">Contacto</Link>
      <Link href="/sobremi">Sobre mi</Link> |{" "}
      <Link href="/admin">Panel de administración</Link> |{" "}
      <Link href="/login">Login</Link> |{" "}
      <Link href="/reservas">Reservas</Link> |{" "}
      </nav>
</header>

<main>
  {children}
  </main>
          </body>
    </html>
  );
}
